# SPDX-License-Identifier: Apache-2.0
if(NOT EXISTS "${REFERENCE}" OR NOT EXISTS "${SEQUENCE}/frame-000008.ppm")
  message("SKIP: no GPU sequence/reference capture")
  return()
endif()
foreach(frame RANGE 0 8)
  if(NOT EXISTS "${SEQUENCE}/frame-00000${frame}.ppm")
    message(FATAL_ERROR "missing sequence frame ${frame}")
  endif()
endforeach()
file(SHA256 "${REFERENCE}" reference_hash)
file(SHA256 "${SEQUENCE}/frame-000000.ppm" first_hash)
file(SHA256 "${SEQUENCE}/frame-000004.ppm" middle_hash)
file(SHA256 "${SEQUENCE}/frame-000008.ppm" last_hash)
if(NOT first_hash STREQUAL reference_hash OR NOT last_hash STREQUAL reference_hash)
  message(FATAL_ERROR "sequence start/return disagrees with static pose")
endif()
if(middle_hash STREQUAL first_hash)
  message(FATAL_ERROR "sequence did not capture its moving pose")
endif()
file(READ "${CAMERA}" camera_json)
string(JSON width GET "${camera_json}" width)
string(JSON height GET "${camera_json}" height)
foreach(matrix IN ITEMS view projection)
  string(JSON length LENGTH "${camera_json}" ${matrix})
  if(NOT length EQUAL 16)
    message(FATAL_ERROR "camera ${matrix} must have 16 elements")
  endif()
endforeach()
file(STRINGS "${SEQUENCE}/frame-000008.ppm" extent LIMIT_COUNT 2)
list(GET extent 1 extent)
if(NOT extent STREQUAL "${width} ${height}")
  message(FATAL_ERROR "camera extent differs from capture")
endif()
