# SPDX-License-Identifier: Apache-2.0
# Compare a paused transport with the old deterministic route, and exercise
# actual wall-clock playback on the same GPU morph fixture.
foreach(mode paused deterministic playing)
  if(mode STREQUAL "playing")
    set(transport --play --playback-speed 0.25 --loop on)
  elseif(mode STREQUAL "deterministic")
    set(transport --time 2 --time-step 0)
  else()
    set(transport --time 2)
  endif()
  execute_process(COMMAND "${VIEWPORT}" --hidden --width 96 --height 96
    --frames 16 --vsync on --overlay off --usd "${SCENE}" ${transport}
    --expect-draws 1 --screenshot "${OUTPUT}-${mode}.ppm"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  file(WRITE "${OUTPUT}-${mode}.log" "${output}\n${error}")
  if(result EQUAL 77)
    message("SKIP: ${output} ${error}")
    return()
  endif()
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "${mode} playback failed: ${output} ${error}")
  endif()
  if(NOT output MATCHES "Uploads: topology=1 points=1 materials=1 textures=0 skins=1 poses=1 morphs=1 morph_weights=([0-9]+) ")
    message(FATAL_ERROR "${mode} playback changed static GPU state: ${output}")
  endif()
  set(weights "${CMAKE_MATCH_1}")
  if(NOT output MATCHES "Animation: Hydra syncs=([0-9]+) time_seconds=")
    message(FATAL_ERROR "missing playback sync evidence: ${output}")
  endif()
  set(syncs "${CMAKE_MATCH_1}")
  if(mode STREQUAL "playing")
    if(weights LESS 2 OR syncs LESS 2)
      message(FATAL_ERROR "wall-clock playback did not animate: ${output}")
    endif()
  elseif(NOT weights EQUAL 1 OR NOT syncs EQUAL 1)
    message(FATAL_ERROR "paused/unchanged time repeated Hydra sync or GPU writes: ${output}")
  endif()
endforeach()
file(SHA256 "${OUTPUT}-paused.ppm" paused)
file(SHA256 "${OUTPUT}-deterministic.ppm" deterministic)
if(NOT paused STREQUAL deterministic)
  message(FATAL_ERROR "paused transport differs from deterministic evaluation")
endif()
