function(toon_configure_openusd)
  find_package(pxr CONFIG REQUIRED)
  if(NOT TARGET hd OR NOT TARGET plug)
    message(FATAL_ERROR
      "The OpenUSD package must provide the hd and plug CMake targets")
  endif()
  set(PXR_INCLUDE_DIRS "${PXR_INCLUDE_DIRS}" PARENT_SCOPE)
endfunction()

# The OpenUSD runtime's root, whose bin/ and lib/ a test puts on PATH.
function(toon_openusd_root out_var)
  if(PXR_INCLUDE_DIRS)
    list(GET PXR_INCLUDE_DIRS 0 _toon_pxr_include)
    get_filename_component(_toon_pxr_root "${_toon_pxr_include}/.." ABSOLUTE)
  elseif(DEFINED pxr_DIR)
    set(_toon_pxr_root "${pxr_DIR}")
  else()
    message(FATAL_ERROR "Could not derive the OpenUSD runtime root")
  endif()
  set(${out_var} "${_toon_pxr_root}" PARENT_SCOPE)
endfunction()
